In [1]:
import pandas as pd
s = pd.Series([10,20,30,40], index=['a','b','c','d'], name="sales")

In [2]:
s

a    10
b    20
c    30
d    40
Name: sales, dtype: int64

In [3]:
s.iloc[0] # it retrieves data from the default index location assigned by the system i.e. 0,1,2,3....
s.loc['a'] # it retrieves data from the index location assigned by us 
s['a'] # it also works without the 'loc' keyword

np.int64(10)

In [4]:
data = {
    'name': ['Alice','Bob','Charlie','Diana','Evan'],
    'age': [25,32,18,47,29],
    'city': ['Kathmandu','Pokhara','Biratnagar','Pokhara','Kathmandu'],
    'salary': [55000,72000,30000,98000,61000]
}
df = pd.DataFrame(data)

df

      name  age        city  salary
0    Alice   25   Kathmandu   55000
1      Bob   32     Pokhara   72000
2  Charlie   18  Biratnagar   30000
3    Diana   47     Pokhara   98000
4     Evan   29   Kathmandu   61000

In [5]:
df.head() # this gives the first 5 data of the dataframe

      name  age        city  salary
0    Alice   25   Kathmandu   55000
1      Bob   32     Pokhara   72000
2  Charlie   18  Biratnagar   30000
3    Diana   47     Pokhara   98000
4     Evan   29   Kathmandu   61000

In [6]:
df.T # dataframe can be transposed as well

                0        1           2        3          4
name        Alice      Bob     Charlie    Diana       Evan
age            25       32          18       47         29
city    Kathmandu  Pokhara  Biratnagar  Pokhara  Kathmandu
salary      55000    72000       30000    98000      61000

In [7]:
df.to_csv('people.csv', index=False) # for converting dataframe to csv file

In [8]:
df_from_csv = pd.read_csv('students.csv') # for retrieving dataframe from a csv file
df_from_csv

,student_id,name,age,grade,city,email,nepali,english,maths,science,social
0,1,Aarav Sharma,16.0,10,Kathmandu,aarav.sharma@example.com,78,88,92,85,80
1,2,Priya Gurung,NaN,9,Pokhara,priya.gurung@example.com,65,76,70,74,72
2,3,Bibek Thapa,17.0,11,Lalitpur,bibek.thapa@example.com,55,65,60,58,62
3,4,Sita Rai,16.0,10,Kathmandu,sita.rai@example.com,89,91,85,88,90
4,5,Anish Karki,NaN,9,Biratnagar,anish.karki@example.com,48,58,52,55,50
5,6,Kritika Shrestha,17.0,11,Kathmandu,kritika.shrestha@example.com,80,84,78,82,86
6,7,Rohan Magar,16.0,10,Pokhara,rohan.magar@example.com,68,72,75,70,66
7,8,Nisha Tamang,NaN,9,Bhaktapur,nisha.tamang@example.com,92,95,90,94,93
8,9,Suman Basnet,18.0,12,Kathmandu,suman.basnet@example.com,60,68,64,66,62
9,10,Alina Adhikari,17.0,11,Lalitpur,alina.adhikari@example.com,75,79,82,80,77
10,11,Deepak Bhandari,16.0,10,Biratnagar,deepak.bhandari@example.com,45,55,50,52,48
11,12,Manisha Poudel,NaN,9,Kathmandu,manisha.poudel@example.com,85,89,91,87,88
12,13,Nabin Khadka,18.0,12,Pokhara,nabin.khadka@example.com,63,73,69,71,67
13,14,Sabina Lama,16.0,10,Kathmandu,sabina.lama@example.com,88,90,86,92,89
14,15,Prakash Rana,17.0,11,Bhaktapur,prakash.rana@example.com,52,61,58,60,56
15,16,Anjali Bista,15.0,9,Lalitpur,anjali.bista@example.com,80,86,84,88,82
16,17,Ramesh Oli,18.0,12,Biratnagar,ramesh.oli@example.com,40,49,45,47,43
17,18,Sunita Chaudhary,16.0,10,Kathmandu,sunita.chaudhary@example.com,90,94,96,93,91
18,19,Kiran Bhattarai,17.0,11,Pokhara,kiran.bhattarai@example.com,70,77,74,76,72
19,20,Puja Neupane,15.0,9,Bhaktapur,puja.neupane@example.com,78,82,80,85,80

In [9]:
students_df = pd.read_csv('students.csv') # for converting csv file to dataframe

In [10]:
new_df = students_df.drop(columns=['student_id', 'grade'])
new_df.describe()

             age     nepali   english      maths   science     social
count  16.000000  20.000000  20.00000  20.000000  20.00000  20.000000
mean   16.562500  70.050000  76.60000  74.050000  75.15000  72.700000
std     0.963933  16.031137  13.67056  15.094352  14.65489  15.437821
min    15.000000  40.000000  49.00000  45.000000  47.00000  43.000000
25%    16.000000  58.750000  67.25000  63.000000  64.50000  62.000000
50%    16.500000  72.500000  78.00000  76.500000  78.00000  74.500000
75%    17.000000  81.250000  88.25000  85.250000  87.25000  86.500000
max    18.000000  92.000000  95.00000  96.000000  94.00000  93.000000

In [11]:
new_df.loc[1:4, ['maths', 'social']] # for slicing/filtering

   maths  social
1     70      72
2     60      62
3     85      90
4     52      50

In [12]:
df_from_csv = pd.read_csv('people.csv')
df_from_csv

      name  age        city  salary
0    Alice   25   Kathmandu   55000
1      Bob   32     Pokhara   72000
2  Charlie   18  Biratnagar   30000
3    Diana   47     Pokhara   98000
4     Evan   29   Kathmandu   61000

In [13]:
people_df = pd.read_csv('people.csv')

In [14]:
people_df.loc[0:4, ['name', 'salary']] # in pandas the ending value of the range is also included unlike numpy

      name  salary
0    Alice   55000
1      Bob   72000
2  Charlie   30000
3    Diana   98000
4     Evan   61000

In [15]:
good_student = new_df[(new_df['maths']>60) & (new_df['nepali']>60)]
good_student

,name,age,city,email,nepali,english,maths,science,social
0,Aarav Sharma,16.0,Kathmandu,aarav.sharma@example.com,78,88,92,85,80
1,Priya Gurung,NaN,Pokhara,priya.gurung@example.com,65,76,70,74,72
3,Sita Rai,16.0,Kathmandu,sita.rai@example.com,89,91,85,88,90
5,Kritika Shrestha,17.0,Kathmandu,kritika.shrestha@example.com,80,84,78,82,86
6,Rohan Magar,16.0,Pokhara,rohan.magar@example.com,68,72,75,70,66
7,Nisha Tamang,NaN,Bhaktapur,nisha.tamang@example.com,92,95,90,94,93
9,Alina Adhikari,17.0,Lalitpur,alina.adhikari@example.com,75,79,82,80,77
11,Manisha Poudel,NaN,Kathmandu,manisha.poudel@example.com,85,89,91,87,88
12,Nabin Khadka,18.0,Pokhara,nabin.khadka@example.com,63,73,69,71,67
13,Sabina Lama,16.0,Kathmandu,sabina.lama@example.com,88,90,86,92,89
15,Anjali Bista,15.0,Lalitpur,anjali.bista@example.com,80,86,84,88,82
17,Sunita Chaudhary,16.0,Kathmandu,sunita.chaudhary@example.com,90,94,96,93,91
18,Kiran Bhattarai,17.0,Pokhara,kiran.bhattarai@example.com,70,77,74,76,72
19,Puja Neupane,15.0,Bhaktapur,puja.neupane@example.com,78,82,80,85,80

In [16]:
result = new_df[new_df['city'] == 'Pokhara'] # filtering
result

,name,age,city,email,nepali,english,maths,science,social
1,Priya Gurung,NaN,Pokhara,priya.gurung@example.com,65,76,70,74,72
6,Rohan Magar,16.0,Pokhara,rohan.magar@example.com,68,72,75,70,66
12,Nabin Khadka,18.0,Pokhara,nabin.khadka@example.com,63,73,69,71,67
18,Kiran Bhattarai,17.0,Pokhara,kiran.bhattarai@example.com,70,77,74,76,72

In [17]:
new_df[new_df['city'].isin(['Kathmandu', 'Pokhara'])] # like an either or condition which will work for multiple values

,name,age,city,email,nepali,english,maths,science,social
0,Aarav Sharma,16.0,Kathmandu,aarav.sharma@example.com,78,88,92,85,80
1,Priya Gurung,NaN,Pokhara,priya.gurung@example.com,65,76,70,74,72
3,Sita Rai,16.0,Kathmandu,sita.rai@example.com,89,91,85,88,90
5,Kritika Shrestha,17.0,Kathmandu,kritika.shrestha@example.com,80,84,78,82,86
6,Rohan Magar,16.0,Pokhara,rohan.magar@example.com,68,72,75,70,66
8,Suman Basnet,18.0,Kathmandu,suman.basnet@example.com,60,68,64,66,62
11,Manisha Poudel,NaN,Kathmandu,manisha.poudel@example.com,85,89,91,87,88
12,Nabin Khadka,18.0,Pokhara,nabin.khadka@example.com,63,73,69,71,67
13,Sabina Lama,16.0,Kathmandu,sabina.lama@example.com,88,90,86,92,89
17,Sunita Chaudhary,16.0,Kathmandu,sunita.chaudhary@example.com,90,94,96,93,91
18,Kiran Bhattarai,17.0,Pokhara,kiran.bhattarai@example.com,70,77,74,76,72

In [18]:
new_df[~new_df['city'].isin(['Kathmandu', 'Pokhara'])] # like neither nor which will exclude the selected values

,name,age,city,email,nepali,english,maths,science,social
2,Bibek Thapa,17.0,Lalitpur,bibek.thapa@example.com,55,65,60,58,62
4,Anish Karki,NaN,Biratnagar,anish.karki@example.com,48,58,52,55,50
7,Nisha Tamang,NaN,Bhaktapur,nisha.tamang@example.com,92,95,90,94,93
9,Alina Adhikari,17.0,Lalitpur,alina.adhikari@example.com,75,79,82,80,77
10,Deepak Bhandari,16.0,Biratnagar,deepak.bhandari@example.com,45,55,50,52,48
14,Prakash Rana,17.0,Bhaktapur,prakash.rana@example.com,52,61,58,60,56
15,Anjali Bista,15.0,Lalitpur,anjali.bista@example.com,80,86,84,88,82
16,Ramesh Oli,18.0,Biratnagar,ramesh.oli@example.com,40,49,45,47,43
19,Puja Neupane,15.0,Bhaktapur,puja.neupane@example.com,78,82,80,85,80

In [19]:
students_df.dropna()

,student_id,name,age,grade,city,email,nepali,english,maths,science,social
0,1,Aarav Sharma,16.0,10,Kathmandu,aarav.sharma@example.com,78,88,92,85,80
2,3,Bibek Thapa,17.0,11,Lalitpur,bibek.thapa@example.com,55,65,60,58,62
3,4,Sita Rai,16.0,10,Kathmandu,sita.rai@example.com,89,91,85,88,90
5,6,Kritika Shrestha,17.0,11,Kathmandu,kritika.shrestha@example.com,80,84,78,82,86
6,7,Rohan Magar,16.0,10,Pokhara,rohan.magar@example.com,68,72,75,70,66
8,9,Suman Basnet,18.0,12,Kathmandu,suman.basnet@example.com,60,68,64,66,62
9,10,Alina Adhikari,17.0,11,Lalitpur,alina.adhikari@example.com,75,79,82,80,77
10,11,Deepak Bhandari,16.0,10,Biratnagar,deepak.bhandari@example.com,45,55,50,52,48
12,13,Nabin Khadka,18.0,12,Pokhara,nabin.khadka@example.com,63,73,69,71,67
13,14,Sabina Lama,16.0,10,Kathmandu,sabina.lama@example.com,88,90,86,92,89
14,15,Prakash Rana,17.0,11,Bhaktapur,prakash.rana@example.com,52,61,58,60,56
15,16,Anjali Bista,15.0,9,Lalitpur,anjali.bista@example.com,80,86,84,88,82
16,17,Ramesh Oli,18.0,12,Biratnagar,ramesh.oli@example.com,40,49,45,47,43
17,18,Sunita Chaudhary,16.0,10,Kathmandu,sunita.chaudhary@example.com,90,94,96,93,91
18,19,Kiran Bhattarai,17.0,11,Pokhara,kiran.bhattarai@example.com,70,77,74,76,72
19,20,Puja Neupane,15.0,9,Bhaktapur,puja.neupane@example.com,78,82,80,85,80

In [20]:
import numpy as np
df_missing = students_df.copy()
df_missing.loc[1, 'age'] = np.nan

In [21]:
subjects = ["nepali", "english", "maths", "science", "social"]
students_df["total_marks"] = students_df[subjects].sum(axis=1)
students_df

,student_id,name,age,grade,city,email,nepali,english,maths,science,social,total_marks
0,1,Aarav Sharma,16.0,10,Kathmandu,aarav.sharma@example.com,78,88,92,85,80,423
1,2,Priya Gurung,NaN,9,Pokhara,priya.gurung@example.com,65,76,70,74,72,357
2,3,Bibek Thapa,17.0,11,Lalitpur,bibek.thapa@example.com,55,65,60,58,62,300
3,4,Sita Rai,16.0,10,Kathmandu,sita.rai@example.com,89,91,85,88,90,443
4,5,Anish Karki,NaN,9,Biratnagar,anish.karki@example.com,48,58,52,55,50,263
5,6,Kritika Shrestha,17.0,11,Kathmandu,kritika.shrestha@example.com,80,84,78,82,86,410
6,7,Rohan Magar,16.0,10,Pokhara,rohan.magar@example.com,68,72,75,70,66,351
7,8,Nisha Tamang,NaN,9,Bhaktapur,nisha.tamang@example.com,92,95,90,94,93,464
8,9,Suman Basnet,18.0,12,Kathmandu,suman.basnet@example.com,60,68,64,66,62,320
9,10,Alina Adhikari,17.0,11,Lalitpur,alina.adhikari@example.com,75,79,82,80,77,393
10,11,Deepak Bhandari,16.0,10,Biratnagar,deepak.bhandari@example.com,45,55,50,52,48,250
11,12,Manisha Poudel,NaN,9,Kathmandu,manisha.poudel@example.com,85,89,91,87,88,440
12,13,Nabin Khadka,18.0,12,Pokhara,nabin.khadka@example.com,63,73,69,71,67,343
13,14,Sabina Lama,16.0,10,Kathmandu,sabina.lama@example.com,88,90,86,92,89,445
14,15,Prakash Rana,17.0,11,Bhaktapur,prakash.rana@example.com,52,61,58,60,56,287
15,16,Anjali Bista,15.0,9,Lalitpur,anjali.bista@example.com,80,86,84,88,82,420
16,17,Ramesh Oli,18.0,12,Biratnagar,ramesh.oli@example.com,40,49,45,47,43,224
17,18,Sunita Chaudhary,16.0,10,Kathmandu,sunita.chaudhary@example.com,90,94,96,93,91,464
18,19,Kiran Bhattarai,17.0,11,Pokhara,kiran.bhattarai@example.com,70,77,74,76,72,369
19,20,Puja Neupane,15.0,9,Bhaktapur,puja.neupane@example.com,78,82,80,85,80,405

In [22]:
def get_remark(total_marks):
    if total_marks > 450:
        return "Excellent"
    elif total_marks > 400:
        return "Very Good"
    elif total_marks > 350:
        return "Good"
    else:
        return "Need Improvement"

students_df["remark"] = students_df["total_marks"].apply(get_remark)

students_df

,student_id,name,age,grade,city,email,nepali,english,maths,science,social,total_marks,remark
0,1,Aarav Sharma,16.0,10,Kathmandu,aarav.sharma@example.com,78,88,92,85,80,423,Very Good
1,2,Priya Gurung,NaN,9,Pokhara,priya.gurung@example.com,65,76,70,74,72,357,Good
2,3,Bibek Thapa,17.0,11,Lalitpur,bibek.thapa@example.com,55,65,60,58,62,300,Need Improvement
3,4,Sita Rai,16.0,10,Kathmandu,sita.rai@example.com,89,91,85,88,90,443,Very Good
4,5,Anish Karki,NaN,9,Biratnagar,anish.karki@example.com,48,58,52,55,50,263,Need Improvement
5,6,Kritika Shrestha,17.0,11,Kathmandu,kritika.shrestha@example.com,80,84,78,82,86,410,Very Good
6,7,Rohan Magar,16.0,10,Pokhara,rohan.magar@example.com,68,72,75,70,66,351,Good
7,8,Nisha Tamang,NaN,9,Bhaktapur,nisha.tamang@example.com,92,95,90,94,93,464,Excellent
8,9,Suman Basnet,18.0,12,Kathmandu,suman.basnet@example.com,60,68,64,66,62,320,Need Improvement
9,10,Alina Adhikari,17.0,11,Lalitpur,alina.adhikari@example.com,75,79,82,80,77,393,Good
10,11,Deepak Bhandari,16.0,10,Biratnagar,deepak.bhandari@example.com,45,55,50,52,48,250,Need Improvement
11,12,Manisha Poudel,NaN,9,Kathmandu,manisha.poudel@example.com,85,89,91,87,88,440,Very Good
12,13,Nabin Khadka,18.0,12,Pokhara,nabin.khadka@example.com,63,73,69,71,67,343,Need Improvement
13,14,Sabina Lama,16.0,10,Kathmandu,sabina.lama@example.com,88,90,86,92,89,445,Very Good
14,15,Prakash Rana,17.0,11,Bhaktapur,prakash.rana@example.com,52,61,58,60,56,287,Need Improvement
15,16,Anjali Bista,15.0,9,Lalitpur,anjali.bista@example.com,80,86,84,88,82,420,Very Good
16,17,Ramesh Oli,18.0,12,Biratnagar,ramesh.oli@example.com,40,49,45,47,43,224,Need Improvement
17,18,Sunita Chaudhary,16.0,10,Kathmandu,sunita.chaudhary@example.com,90,94,96,93,91,464,Excellent
18,19,Kiran Bhattarai,17.0,11,Pokhara,kiran.bhattarai@example.com,70,77,74,76,72,369,Good
19,20,Puja Neupane,15.0,9,Bhaktapur,puja.neupane@example.com,78,82,80,85,80,405,Very Good

In [23]:
def percentage(total_marks):
    return f"{(total_marks / 500) * 100:.2f}%"

students_df["percentage"] = students_df["total_marks"].apply(percentage)

students_df

,student_id,name,age,grade,city,email,nepali,english,maths,science,social,total_marks,remark,percentage
0,1,Aarav Sharma,16.0,10,Kathmandu,aarav.sharma@example.com,78,88,92,85,80,423,Very Good,84.60%
1,2,Priya Gurung,NaN,9,Pokhara,priya.gurung@example.com,65,76,70,74,72,357,Good,71.40%
2,3,Bibek Thapa,17.0,11,Lalitpur,bibek.thapa@example.com,55,65,60,58,62,300,Need Improvement,60.00%
3,4,Sita Rai,16.0,10,Kathmandu,sita.rai@example.com,89,91,85,88,90,443,Very Good,88.60%
4,5,Anish Karki,NaN,9,Biratnagar,anish.karki@example.com,48,58,52,55,50,263,Need Improvement,52.60%
5,6,Kritika Shrestha,17.0,11,Kathmandu,kritika.shrestha@example.com,80,84,78,82,86,410,Very Good,82.00%
6,7,Rohan Magar,16.0,10,Pokhara,rohan.magar@example.com,68,72,75,70,66,351,Good,70.20%
7,8,Nisha Tamang,NaN,9,Bhaktapur,nisha.tamang@example.com,92,95,90,94,93,464,Excellent,92.80%
8,9,Suman Basnet,18.0,12,Kathmandu,suman.basnet@example.com,60,68,64,66,62,320,Need Improvement,64.00%
9,10,Alina Adhikari,17.0,11,Lalitpur,alina.adhikari@example.com,75,79,82,80,77,393,Good,78.60%
10,11,Deepak Bhandari,16.0,10,Biratnagar,deepak.bhandari@example.com,45,55,50,52,48,250,Need Improvement,50.00%
11,12,Manisha Poudel,NaN,9,Kathmandu,manisha.poudel@example.com,85,89,91,87,88,440,Very Good,88.00%
12,13,Nabin Khadka,18.0,12,Pokhara,nabin.khadka@example.com,63,73,69,71,67,343,Need Improvement,68.60%
13,14,Sabina Lama,16.0,10,Kathmandu,sabina.lama@example.com,88,90,86,92,89,445,Very Good,89.00%
14,15,Prakash Rana,17.0,11,Bhaktapur,prakash.rana@example.com,52,61,58,60,56,287,Need Improvement,57.40%
15,16,Anjali Bista,15.0,9,Lalitpur,anjali.bista@example.com,80,86,84,88,82,420,Very Good,84.00%
16,17,Ramesh Oli,18.0,12,Biratnagar,ramesh.oli@example.com,40,49,45,47,43,224,Need Improvement,44.80%
17,18,Sunita Chaudhary,16.0,10,Kathmandu,sunita.chaudhary@example.com,90,94,96,93,91,464,Excellent,92.80%
18,19,Kiran Bhattarai,17.0,11,Pokhara,kiran.bhattarai@example.com,70,77,74,76,72,369,Good,73.80%
19,20,Puja Neupane,15.0,9,Bhaktapur,puja.neupane@example.com,78,82,80,85,80,405,Very Good,81.00%